

# YELLOW_DETECTOR
THRES: 0.01
YELLOW: [0, 255, 255]
HUE_LIMIT: 10

# HEADING
IMG_NUM_ROWS: 240
IMG_NUM_COLS: 320
ALPHA: 0.63
BETA: 111

# FOLLOW
THETA_TOLERANCE: 0.2 # RAD
LINEAR_SPEED: 0.2 # M/S
ANGULAR_SPEED: 30 # DEGREE/S
FOLLOW_DISTANCE: 0.5 # M

# AVOID
DIAMETER: 0.07 # M
DISTANCE_TOLERANCE: 0.2 # M
FORESIGHT_TIMESTAMPS: [0.0, 0.2, 0.4, 0.6]
SAMPLE_ANGLE: 5