

# yellow_detector
THRES: 0.01

# heading
img_num_rows: 240
img_num_cols: 320
alpha: 0.63
beta: 111

# follow
theta_tolerance: 0.2 # rad
linear_spd: 0.2 # m/s
angular_speed: 30 # degree/s
follow_distance: 0.5 # m

# avoid
diameter: 0.07 # m
distance_tolerance: 0.2 # m
foresight_timestamps: [0.0, 0.2, 0.4, 0.6]
sample_angle: 5 